name: Terraform Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  validate:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup TfSec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true